import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dasuni
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int role;
    public Login() {
        initComponents();
    }
    
    public Login(int role){
        this.role=role;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblUserNameSignIn = new javax.swing.JLabel();
        lblPassWordSignIn = new javax.swing.JLabel();
        txtUsernameSignIn = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        lblUserNameSignUp = new javax.swing.JLabel();
        lblPassWordSignUp = new javax.swing.JLabel();
        lblRePassWordSignUp = new javax.swing.JLabel();
        txtUserNameSignUp = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University Management System Login");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserNameSignIn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUserNameSignIn.setText("User Name");
        lblUserNameSignIn.setName(""); // NOI18N
        getContentPane().add(lblUserNameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        lblPassWordSignIn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPassWordSignIn.setText("Pass Word");
        getContentPane().add(lblPassWordSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtUsernameSignIn.setText("chamodi");
        getContentPane().add(txtUsernameSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 220, 20));

        btnSignIn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        lblUserNameSignUp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUserNameSignUp.setText("User Name");
        getContentPane().add(lblUserNameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lblPassWordSignUp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPassWordSignUp.setText("Pass word");
        getContentPane().add(lblPassWordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        lblRePassWordSignUp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRePassWordSignUp.setText("Re enter Pass Word");
        getContentPane().add(lblRePassWordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));
        getContentPane().add(txtUserNameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 220, -1));

        btnSignUp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Sign In");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Sign Up");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 170, 90, 30));

        jPasswordField1.setText("123");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 220, -1));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 220, -1));
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 220, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Index No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 220, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        String a=txtUsernameSignIn.getText();
        String b=String.valueOf(jPasswordField1.getPassword());
        
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/UniversityManagementSystem","root","");
            Statement st=con.createStatement();
            String query="";
            if(role==1){
                query = "SELECT * FROM Lecturer WHERE UserName ='"+a+"' AND Password='"+b+"' ;"; 
            }else{
                query = "SELECT * FROM Student WHERE UserName ='"+a+"' AND Password='"+b+"' ;";
            }
            ResultSet rs= st.executeQuery(query);
            
            if(rs.next()){
                //System.out.println("\nDOne");
                Frame2 x=new Frame2(a,role);
                x.setVisible(true);
                this.dispose();      
            }else{
             System.out.println("Error!");
            }
            con.close();
            
        }
        catch (Exception e)
        {
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f, "Error\n" +e);
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        String Username=txtUserNameSignUp.getText();
        String p1=String.valueOf(jPasswordField2.getPassword());
        String p2=String.valueOf(jPasswordField3.getPassword());
        String index=jTextField2.getText();
        
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/UniversityManagementSystem","root","");
            
            String query="";
	    if(p1.equals(p2)){
            	if(role==1){
                	query = "INSERT INTO Lecturer (Name, UserName, Password, IndexNo) VALUES ('"+name+"','"+Username+"','"+p1+"','"+index+"') ;"; 
            }else{
                query = "INSERT INTO Student (Name, UserName, Password, IndexNo) VALUES ('"+name+"','"+Username+"','"+p1+"', '"+index+"') ;";
            }
                System.out.println("Done!!");
	    }
	    else{
		System.out.println("Error!");
	    }
            PreparedStatement st=con.prepareStatement(query);
            st.executeUpdate();
            
           
                
                Frame2 y=new Frame2(Username,role);
                y.setVisible(true);
                this.dispose();      
            
            con.close();
            
        }
        catch (Exception e)
        {
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f, "Error\n" +e);
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblPassWordSignIn;
    private javax.swing.JLabel lblPassWordSignUp;
    private javax.swing.JLabel lblRePassWordSignUp;
    private javax.swing.JLabel lblUserNameSignIn;
    private javax.swing.JLabel lblUserNameSignUp;
    private javax.swing.JTextField txtUserNameSignUp;
    private javax.swing.JTextField txtUsernameSignIn;
    // End of variables declaration//GEN-END:variables
}
